[package]
name = "mysql-wrapper"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mysql-wrapper"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
nix.workspace = true
axum.workspace = true
mysql_async = { version = "0.37.0", default-features = false, features = ["default-rustls"] }
reqwest.workspace = true
uuid = { version = "1.24.0", features = ["v5"] }
